### PR TITLE
Correct the publisher name for Breakfast Cult

### PR DESCRIPTION
**Pull request by szabba**
* I assume the publisher changes somewhere between the publishing of Breakfast Cult and the non-Fate Hard Wired Island.
    * Paul Matijevic (the author of Breakfast Cult) is def involved in Weird Age Games.
      Their [itch.io page] uses his nickname as part of the URL _and_ links to his Twitter profile as the one for Weird Age Games.
* Also adding a non-Breakfast Cult setting for Fate to the list.

[itch.io page]: https://ettin.itch.io/

### CODE REVIEW

**Comment by szabba** [comment]
I assume we'll want to wait with this until #3 is resolved, @amazingrando ?

**Comment by amazingrando** [comment]
@szabba I have merged #3. You can update your PR and I'll get it in. Thanks!

**Comment by szabba** [comment]
@amazingrando @johnhelmuth updated.

**Comment by johnhelmuth** [comment]
This PR looks good to me, verified current publisher (as described by @szabba) and that the new links are working.

**Review by johnhelmuth — COMMENTED** [review]
Done.

**Pull request merged**
