### PR TITLE
Sorted CSV

### PR DESCRIPTION
**Pull request by amazingrando**
Using macOS' Numbers app, I sorted the CSV by Publisher, then Title.

## To review this PR:
- [ ] Confirm the changes in sorting

### CODE REVIEW

**Comment by johnhelmuth** [comment]
I think we are going to have to agree on a sorting collation to use for the check (which is `en_US.UTF-8`) to get consistent results.

Tonight, I will see if it's possible to change the configuration for Mac OS Numbers to do this, or what it is using and change the Check CSV order check to match that... and add something to the README about how to sort it before commits using that collation order.

Alternatively, we could add a script to do the sorting as part of a "build process", where we also set the package.json version number (Issue #10), which would run as part of a Github Action, allow it to be sorted and the sort checked with the same configuration.

**Comment by amazingrando** [comment]
I'm good with whatever you decide on for sorting standards.

**Comment by johnhelmuth** [comment]
Merging this branch, adding a "test" script to package.json in a different PR that will do the check order step in a system agnostic way, so that we do not have to make sure we are all using the same tools to re-order the list.

**Review by johnhelmuth — APPROVED** [review]
This ordering looks good to me if it's good to @amazingrando, and it works with the code to check ordering in the a new PR to come.

**Pull request merged**
